const USER_JOINED = 'USER_JOINED'
const GAME_CREATED = 'GAME_CREATED'
const SELF_JOINED = 'SELF_JOINED'
const ATTEMPTED_TO_JOIN_EXPIRED = 'ATTEMPTED_TO_JOIN_EXPIRED'

export {
  USER_JOINED,
  GAME_CREATED,
  SELF_JOINED,
  ATTEMPTED_TO_JOIN_EXPIRED
}