const GAME_CREATED = 'GAME_CREATED'
const ATTEMPTED_TO_JOIN_EXPIRED = 'ATTEMPTED_TO_JOIN_EXPIRED'
const SELF_JOINED = 'SELF_JOINED'
const USER_JOINED = 'USER_JOINED'
const USER_LEFT = 'USER_LEFT'

export {
  GAME_CREATED,
  ATTEMPTED_TO_JOIN_EXPIRED,
  SELF_JOINED,
  USER_JOINED,
  USER_LEFT
}